apiVersion: v1
kind: Service
metadata:
  name: ibmimsr
spec:
  selector:
    app: ibmimsr
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32000